// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
.........fffff..........
..........ffff..........
..........fff...........
...........ff...........
............f...........
`;
            case "image3":return img`
. . . . . . . c c c a c . . . . 
. . c c b b b a c a a a c . . . 
. c c a b a c b a a a b c c . . 
. c a b c f f f b a b b b a . . 
. c a c f f f 8 a b b 3 b b a . 
. c a 8 f f 8 c a b b b b b a . 
c c c a c c c 3 a b c f a b c c 
c c a a a c c c a c f f c b b a 
c c a b 6 a c c a f f c c b b a 
c a b c 8 6 c 3 a a a b b c b c 
c a c f f a c c a f a c c c b . 
c a 8 f c c b a f f c b c c c . 
. c b c c c c b f c a b b a c . 
. . a b b b b b b b b b b b c . 
. . . c c c c b b b b b c c . . 
. . . . . . . . c b b c . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
