namespace StatusBarKind {
    export const Points = StatusBarKind.create()
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.collectibleRedCrystal, function (sprite, location) {
    if (true) {
        info.changeScoreBy(1)
        tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleBlueCrystal)
        info.startCountdown(7)
    }
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    .........fffff..........
    ..........ffff..........
    ..........fff...........
    ...........ff...........
    ............f...........
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 75, 75)
tiles.setTilemap(tilemap`level1`)
tiles.placeOnRandomTile(mySprite, sprites.dungeon.collectibleBlueCrystal)
scene.cameraFollowSprite(mySprite)
info.startCountdown(7)
